### PR TITLE
link to examples

### PR DESCRIPTION
**Pull request by ontouchstart**
I created a gh-pages branch to my fork and add links to the example files. Now they can be hosted on Github Pages. Perhaps you guys can do that as well. 

See examples here: https://ontouchstart.github.io/template/

Thanks.

### CODE REVIEW

**Comment by chrisgervang** [comment]
Could you please re-add the dev instructions to the readme?

**Comment by ontouchstart** [comment]
I put the dev instruction back. The README.md should look good in the context of repo itself: https://github.com/ontouchstart/template/tree/gh-pages

However, on the front page GitHub automatically generated from that README.md file: https://ontouchstart.github.io/template/ the dev instruction looks out of context. A possible solution is to add a root index.html as a front page.

**Comment by shancarter** [comment]
We host the getting started page on distill:
http://distill.pub/guide/

**Comment by shancarter** [comment]
Thanks, but we're committed to keeping the hosted pages on distill.pub domain, I don't want to divide the information among multiple domains.

**Comment by ontouchstart** [comment]
Understand. The user forked gh-pages are just for quick template tests without a server. Perhaps I should put it in a different repo.

**Pull request closed without merging**
